name: Continous Integration

# this is trigeer CI on push and PR for main branch only
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# this is trigger CI on all kinds of branches and PRs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: unbuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install Deps
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run formatter
        run: npm run format
